### ISSUE TITLE
xml lib updated yesterday to 3.3.0, pub activate start to fail

### ISSUE THREAD

**Issue by nanzhang1** [TOPdesk/dart-junitreport#13]
Resolving dependencies...
+ args 1.5.1
+ charcode 1.1.2
+ collection 1.14.11
+ convert 2.1.1
+ intl 0.15.7
+ junitreport 0.3.3
+ path 1.6.2
+ petitparser 2.1.1
+ testreport 0.3.1
+ typed_data 1.1.6
+ xml 3.3.0
Precompiling executables...
Failed to precompile junitreport:tojunit:
file:///data/jenkins/.pub-cache/hosted/pub.dartlang.org/junitreport-0.3.3/lib/src/impl/xml.dart:6:8: Error: Error when reading 'file:///data/jenkins/.pub-cache/hosted/pub.dartlang.org/xml-3.3.0/lib/xml/visitors/pretty_writer.dart': No such file or directory
import 'package:xml/xml/visitors/pretty_writer.dart';
       ^
file:///data/jenkins/.pub-cache/hosted/pub.dartlang.org/junitreport-0.3.3/lib/src/impl/xml.dart:28:23: Error: Method not found: 'XmlPrettyWriter'.
  document.accept(new XmlPrettyWriter(buffer, 0, '  '));
                      ^^^^^^^^^^^^^^^
file:///data/jenkins/.pub-cache/hosted/pub.dartlang.org/junitreport-0.3.3/lib/src/impl/xml.dart:28:38: Error: Too many positional arguments: 0 allowed, but 3 found.
Try removing the extra positional arguments.
  document.accept(new XmlPrettyWriter(buffer, 0, '  '));

**Comment by rspilker** [comment]
Created https://github.com/renggli/dart-xml/issues/55 to track if we can use a better API.

**Comment by rspilker** [comment]
thanks for reporting, please let me know if this actually fixed your problems.

**Comment by nanzhang1** [comment]
@rspilker  I am still getting this error when pub activate:
pub.dartlang.org/xml-3.3.1/lib/xml/visitors/pretty_writer.dart': No such file or directory

**Comment by rspilker** [comment]
The issue I created has been fixed, and I just releases 1.0.1 that should fix this problem. Can you confirm it works now?

**Comment by nanzhang1** [comment]
@rspilker  Hi is there any reason why it requires dart 2.1+? The stable flutter channel has dart 2.1.0 dev, we 'll have to use beta version if we want to use this library.

**Comment by rspilker** [comment]
Shall I change that to `'^2.0.0'`? do you have another suggestion?

**Comment by nanzhang1** [comment]
if you can, change to '^2.0.0' would be easier for us to use this in our flutter project.

**Comment by renggli** [comment]
Sorry for breaking this library. I've submitted a pull request (https://github.com/TOPdesk/dart-junitreport/pull/16) that should work with older and newer version of `xml`.

**Comment by rspilker** [comment]
Thanks. I just merged it.
