### ISSUE TITLE
use together with --coverage will be error

### ISSUE THREAD

**Issue by NanYeYe** [TOPdesk/dart-junitreport#18]
`flutter test --machine --coverage | tojunit > test-results.xml`
Error Msg:
![image](https://user-images.githubusercontent.com/11953895/81782745-daca1d80-952c-11ea-9b82-26a9300b2c02.png)

**Comment by doublej74** [comment]
+1 
I can confirm that switching the paramaters give the same error

**Comment by kuhnroyal** [comment]
See https://github.com/flutter/flutter/issues/56675#issuecomment-631097647

**Comment by rspilker** [comment]
My first try to reproduce this gave:
```
$ flutter test --machine --coverage > withcoverage.txt
The test command doesn't support --machine and coverage together
```

I'll update flutter and see if it is allowed in a later version/

**Comment by kuhnroyal** [comment]
Thanks for the fix, I think excluding any invalid line is good even if they fix it in Flutter, makes it a little more future/failure proof.
