### ISSUE TITLE
Update/relax dependency on xml

### ISSUE THREAD

**Issue by MichaelMarner** [TOPdesk/dart-junitreport#19]
This library depends on `xml: ^3.7.0` which is now quite old (latest version is 4.3.0). Depending on the older version is causing version conflicts in our apps which now need newer versions.

Would it be possible to relax the version requirement to allow the latest version of xml?

Thanks
Michael

**Comment by mreichelt** [comment]
It would be really nice if this could be fixed, because this currently is the only package versioning issue we have in our current project. Also, currently we can't upgrade to Flutter 1.20 because of this.

**Comment by MichaelMarner** [comment]
@mreichelt 

As a workaround until #20 is merged, you can specify your dependency overrides like so:

```yaml
dependency_overrides:
  xml: ^4.3.0
  flutter_svg: 0.18.0
```

And you can start using Flutter 1.20 (this is what we are doing for the time being)

**Comment by rspilker** [comment]
Sorry for the late response. I've been on holiday.

The initial reason not to upgrade to 4.1.0 was a [regression in the handling of whitespace](https://github.com/renggli/dart-xml/issues/78). Now, there is a way to retain the whitespace, and can we upgrade to a later version.

So the change is not just changing the pubspec files, but also add the predicate.

I will try to release a new version later today.

I am wondering about your setup. The reason why I added the `pubspec.lock` file is that I think of `junitreport:tojunit` as a standalone application hat you would invoke in your pipeline. In normal projects, I wouldn't expect dependencies on `junitreport`, only in other standalone test applications.

Can you explain why you have a dependency from your flutter app to `junitreport`? Is there something I'm missing?

**Comment by MichaelMarner** [comment]
It's fairly standard to add tooling, such as this project to `dev_dependencies`, so that they get installed along with the project, and are available without having to do `pub activate`.

Our CI job, for example, does the following:

```
flutter packages get  # includes junitreport as a dev dependency
flutter test --machine > test_output.json
flutter pub run junitreport:tojunit --input test_output.json --output reports/test-results.xml
```

**Comment by rspilker** [comment]
Thanks for the feedback and explanation.

**Comment by MichaelMarner** [comment]
No worries, I didn't know about the 4.1.0 regression - regardless happy it's fixed 👍
