### ISSUE TITLE
The --machine flag is only valid with the --version flag.

### ISSUE THREAD

**Issue by Abhishek01039** [TOPdesk/dart-junitreport#21]
When I have tried 
```flutter drive --target=test_driver/tests/splash_screen.dart --no-build --no-pub --machine > example.jsonl```
I am getting this error
```The --machine flag is only valid with the --version flag.```

**Comment by Abhishek01039** [comment]
@daniel-v 
can you please look into this?
Thanks

**Comment by daniel-v** [comment]
I think you got misdirected a little bit. The command example you pasted doesn't concern this repository. Try asking this question on Flutter's repo.

**Comment by rspilker** [comment]
@daniel-v thanks for answering this question.

**Comment by Abhishek01039** [comment]
Thanks @daniel-v
