### ISSUE TITLE
Create output directory

### ISSUE THREAD

**Issue by quirijnAtPropertyMe** [TOPdesk/dart-junitreport#22]
Hi, Thanks for the great tool!

I like to put all my reports into a separate directory, ie `reports`.

Currently 
```
tojunit -o reports/test.xml
```
will fail because `reports` does not exist. 
Creating the directory ahead of time is trivial, it would be a nice experience if the tool would go ahead on make all the directories.

Cheers!

**Comment by rspilker** [comment]
I'm still a bit in the fence here. I understand the convenience this would give. 

On the other hand, I've personally been bitten by a typo or mistake where I ended up with loads of directories in unexpected places, that I only discovered weeks after they had been created.

I also don't want to add an extra command line parameter just for this feature.

So, I'm not convinced yet if this would be a good feature to offer. I'm keeping the issue open until I've made up my mind. Any input is welcome.

**Comment by quirijnAtPropertyMe** [comment]
For me it's just a matter of expectation. 
From my experience with other CLI tools I expected that it would create the directories.
Happy with any decision you decide to take 😄

**Comment by fredgrott** [comment]
I would say no to this as one can in fact use derry to automate creating the dirs we need even on the CI side and for that matter we can can also use Grinder to do the same thing IMHO

**Comment by rspilker** [comment]
I've decided not to implement this. Sorry.
