### ISSUE TITLE
Exception: "Bad state: not started"

### ISSUE THREAD

**Issue by kluverua** [TOPdesk/dart-junitreport#27]
After running this command `flutter test --machine | tojunit --output TEST-report.xml`
I get an error `Bad state: not started` and empty **TEST-report.xml** file
At the same time this command `flutter test --machine` work well and writes correct results to console.

This behavior appeared after flutter update
flater version 2.0.3.
junitreport version 1.3.1.

**Comment by kluverua** [comment]
I fixed this error by upgrading this library to null safety version [(fixed sorces)](https://github.com/TOPdesk/dart-junitreport/files/6249002/junitreport_nullsafety.zip)

For those who faced the same problem: You can take fixed **exe** file from [archive](https://github.com/TOPdesk/dart-junitreport/files/6249002/junitreport_nullsafety.zip) or compile it yourself: `dart compile exe bin/tojunit.dart`

**Comment by rspilker** [comment]
A null-safe version 2.0.0 has just been released.
