### ISSUE TITLE
Update dependencies, and lockfile

### ISSUE THREAD

**Issue by daniel-v** [TOPdesk/dart-junitreport#3]
I imagine it's been a while since `pubspec.lock` was last regenerated. It might be a good idea to update it.
With later versions of SDK, some packages just got newer versions (such as collection and test).

I've tested things locally, functionality does not seem to break.

**Comment by rspilker** [comment]
Thanks for the reminder, I will update the dependencies before the next release, which will be done after merging #2 

Köszönöm

**Comment by rspilker** [comment]
Done in https://github.com/TOPdesk/dart-junitreport/commit/ebb32cd3c489736f5ad93a548458879684d510bb
