### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by raapperez** [TOPdesk/dart-junitreport#30]
Hi, we use a lot `dart-junitreport`. Thank you for creating it.

We are bumping flutter in our project and require some of the dependencies to be updated.

It would be perfect if the following dependencies are bumped to the last version:
```
  args: ^2.1.0
  intl: ^0.17.0
  xml: ^5.1.0
```

**Comment by rspilker** [comment]
A null-safe version 2.0.0 has just been released.
