### ISSUE TITLE
Could you help to support flutter 2.13.0 of null safety?

### ISSUE THREAD

**Issue by yuanhuiliu** [TOPdesk/dart-junitreport#32]
Hello rspilker, we use this dart-junitreport tool in our Jenkins to generate junit-version xml test report. Recently we upgraded flutter to 2.13 to support null safety, but tool dart-junitreport doesn't provide a null safety version. So could you please help to update this tool to support null safety? Thx!

**Comment by yuanhuiliu** [comment]
I tried to use the version you provided in #27  and got the same result: `Bad state: not started` and empty TEST-report.xml file. I run my test cases in this docker image: `cirrusci/flutter:2.2.3`. This docker image is found from [docker hub](https://hub.docker.com/r/cirrusci/flutter/tags?page=1&ordering=last_updated)

**Comment by rspilker** [comment]
A null-safe version 2.0.0 has just been released.
