### ISSUE TITLE
Failed tests being reported as "Error" instead of "Failure"

### ISSUE THREAD

**Issue by JordanRoberts1** [TOPdesk/dart-junitreport#33]
As the title states. A failed test is being reported as an "Error" instead of a "Failure". See image below:

![image](https://user-images.githubusercontent.com/43049401/127554092-90c91771-0c4d-4431-9371-b306d095b44a.png)

This seems odd to me, but maybe this is intentional? If it is intentional, what constitutes an "Error" vs a "Failure"?

**Comment by rspilker** [comment]
A failure is a test that `fails`. Like: 
```Dart
expect(1, 2);
```

An error is that an exception occurred during the execution of the test.
```Dart
int.parse('avogadro's number');
```

In tis case, it actually is really an error, because an exception was caught by the "FLUTTER TEST FRAMEWORK".

**Comment by rspilker** [comment]
May I suggest you add `-b "/var/jenkins-home/workspace/ure-hdwsurp-100-testing-pipeline"` to the `tojunit` command line to remove that text from the package name.

See `tojunit -h` for all command line options.
